// <auto-generated />
using System;
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260514135118_SeedAdminData")]
    partial class SeedAdminData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Models.Ban", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBan");

                    b.ToTable("Bans");

                    b.HasData(
                        new
                        {
                            MaBan = 1,
                            TenBan = "Bàn số 1",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaBan = 2,
                            TenBan = "Bàn số 2",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaBan = 3,
                            TenBan = "Bàn số 3",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaBan = 4,
                            TenBan = "Bàn VIP 1",
                            TrangThai = "Trong"
                        });
                });

            modelBuilder.Entity("BE.Models.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float>("ThanhTien")
                        .HasColumnType("real");

                    b.HasKey("MaHD", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("BE.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<float>("SoLuong")
                        .HasColumnType("real");

                    b.Property<float>("ThanhTien")
                        .HasColumnType("real");

                    b.HasKey("MaPN", "MaNL");

                    b.HasIndex("MaNL");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("BE.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangSoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhuyenMaiMaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThuNganMaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHD");

                    b.HasIndex("KhachHangSoDienThoai");

                    b.HasIndex("KhuyenMaiMaKM");

                    b.HasIndex("MaBan");

                    b.HasIndex("ThuNganMaNV");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("BE.Models.KhachHang", b =>
                {
                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoDienThoai");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BE.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTramGiam")
                        .HasColumnType("real");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMais");

                    b.HasData(
                        new
                        {
                            MaKM = "KHAITRUONG",
                            HanSuDung = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 20f
                        },
                        new
                        {
                            MaKM = "CHAO_PHONG",
                            HanSuDung = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 10f
                        });
                });

            modelBuilder.Entity("BE.Models.MonAn", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMon");

                    b.ToTable("MonAns");

                    b.HasData(
                        new
                        {
                            MaMon = "M01",
                            GiaTien = 150000f,
                            TenMon = "Bít tết sốt tiêu đen",
                            TrangThai = "DangBan"
                        },
                        new
                        {
                            MaMon = "M02",
                            GiaTien = 65000f,
                            TenMon = "Salad cá ngừ",
                            TrangThai = "DangBan"
                        },
                        new
                        {
                            MaMon = "M03",
                            GiaTien = 30000f,
                            TenMon = "Nước ép dưa hấu",
                            TrangThai = "DangBan"
                        });
                });

            modelBuilder.Entity("BE.Models.NguyenLieu", b =>
                {
                    b.Property<string>("MaNL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("DonGia")
                        .HasColumnType("real");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaTriTon")
                        .HasColumnType("real");

                    b.Property<float>("SoLuongTon")
                        .HasColumnType("real");

                    b.Property<string>("TenNL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNL");

                    b.ToTable("NguyenLieus");

                    b.HasData(
                        new
                        {
                            MaNL = "NL02",
                            DonGia = 0f,
                            DonViTinh = "Kg",
                            GiaTriTon = 0f,
                            SoLuongTon = 0f,
                            TenNL = "Thịt Bò Úc"
                        },
                        new
                        {
                            MaNL = "NL03",
                            DonGia = 0f,
                            DonViTinh = "Kg",
                            GiaTriTon = 0f,
                            SoLuongTon = 0f,
                            TenNL = "Cà chua Đà Lạt"
                        },
                        new
                        {
                            MaNL = "NL04",
                            DonGia = 0f,
                            DonViTinh = "Thùng",
                            GiaTriTon = 0f,
                            SoLuongTon = 0f,
                            TenNL = "Bia Heineken"
                        });
                });

            modelBuilder.Entity("BE.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanViens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("NhanVien");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BE.Models.PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaCungCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.HasKey("MaPN");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("BE.Models.Admin", b =>
                {
                    b.HasBaseType("BE.Models.NhanVien");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("BE.Models.ThuNgan", b =>
                {
                    b.HasBaseType("BE.Models.NhanVien");

                    b.HasDiscriminator().HasValue("ThuNgan");
                });

            modelBuilder.Entity("BE.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("BE.Models.HoaDon", "HoaDon")
                        .WithMany("DanhSachChiTiet")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.MonAn", "MonAn")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("BE.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("BE.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaNL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("DanhSachChiTiet")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("BE.Models.HoaDon", b =>
                {
                    b.HasOne("BE.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangSoDienThoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhuyenMaiMaKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.Ban", "Ban")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan");

                    b.HasOne("BE.Models.ThuNgan", "ThuNgan")
                        .WithMany("HoaDonsDaXuLy")
                        .HasForeignKey("ThuNganMaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("ThuNgan");
                });

            modelBuilder.Entity("BE.Models.Ban", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BE.Models.HoaDon", b =>
                {
                    b.Navigation("DanhSachChiTiet");
                });

            modelBuilder.Entity("BE.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BE.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BE.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BE.Models.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("BE.Models.PhieuNhap", b =>
                {
                    b.Navigation("DanhSachChiTiet");
                });

            modelBuilder.Entity("BE.Models.ThuNgan", b =>
                {
                    b.Navigation("HoaDonsDaXuLy");
                });
#pragma warning restore 612, 618
        }
    }
}
