// <auto-generated />
using System;
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Models.Ban", b =>
                {
                    b.Property<int>("MaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBan"));

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBan");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("BE.Models.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float>("ThanhTien")
                        .HasColumnType("real");

                    b.HasKey("MaHD", "MaMon");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("BE.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhachHangSoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KhuyenMaiMaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThuNganMaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("TongTien")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHD");

                    b.HasIndex("KhachHangSoDienThoai");

                    b.HasIndex("KhuyenMaiMaKM");

                    b.HasIndex("MaBan");

                    b.HasIndex("ThuNganMaNV");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("BE.Models.KhachHang", b =>
                {
                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoDienThoai");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BE.Models.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTramGiam")
                        .HasColumnType("real");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("BE.Models.MonAn", b =>
                {
                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GiaTien")
                        .HasColumnType("real");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMon");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("BE.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanViens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("NhanVien");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BE.Models.Admin", b =>
                {
                    b.HasBaseType("BE.Models.NhanVien");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("BE.Models.ThuNgan", b =>
                {
                    b.HasBaseType("BE.Models.NhanVien");

                    b.HasDiscriminator().HasValue("ThuNgan");
                });

            modelBuilder.Entity("BE.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("BE.Models.HoaDon", "HoaDon")
                        .WithMany("DanhSachChiTiet")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.MonAn", "MonAn")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("BE.Models.HoaDon", b =>
                {
                    b.HasOne("BE.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangSoDienThoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhuyenMaiMaKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.Ban", "Ban")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan");

                    b.HasOne("BE.Models.ThuNgan", "ThuNgan")
                        .WithMany("HoaDonsDaXuLy")
                        .HasForeignKey("ThuNganMaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("ThuNgan");
                });

            modelBuilder.Entity("BE.Models.Ban", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BE.Models.HoaDon", b =>
                {
                    b.Navigation("DanhSachChiTiet");
                });

            modelBuilder.Entity("BE.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BE.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BE.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BE.Models.ThuNgan", b =>
                {
                    b.Navigation("HoaDonsDaXuLy");
                });
#pragma warning restore 612, 618
        }
    }
}
